background = #0c0912
foreground = #ffffff

cursor-color = #b39aff
cursor-text = #0c0912

selection-background = #b39aff
selection-foreground = #0c0912

# normal colors
palette = 0=#14121a
palette = 1=#f66f81
palette = 2=#22ff73
palette = 3=#f9b44e
palette = 4=#6c3bff
palette = 5=#b39aff
palette = 6=#827a89
palette = 7=#ffffff

# bright colors
palette = 8=#3b3440
palette = 9=#f66f81
palette = 10=#22ff73
palette = 11=#f9b44e
palette = 12=#b39aff
palette = 13=#6c3bff
palette = 14=#827a89
palette = 15=#ffffff
