## name: Vite
## author: VoidZero

background #0c0912
foreground #ffffff
selection_background #b39aff
selection_foreground #0c0912
url_color #b39aff
cursor #b39aff
cursor_text_color #0c0912

# Tabs
active_tab_background #b39aff
active_tab_foreground #0c0912
inactive_tab_background #14121a
inactive_tab_foreground #827a89

# Windows
active_border_color #b39aff
inactive_border_color #3b3440

# normal
color0 #14121a
color1 #f66f81
color2 #22ff73
color3 #f9b44e
color4 #6c3bff
color5 #b39aff
color6 #827a89
color7 #ffffff

# bright
color8 #3b3440
color9 #f66f81
color10 #22ff73
color11 #f9b44e
color12 #b39aff
color13 #6c3bff
color14 #827a89
color15 #ffffff

# extended colors
color16 #f9b44e
color17 #f66f81
